// Writes src/abi.ts from the compiled MORCastEscrow artifact: the contract's ABI and the
// keccak256 hash of its runtime code. Run `forge build` first; Foundry's `cast` computes the hash,
// because Node's crypto module has no Keccak-256.
// With --check, exits with an error if src/abi.ts is out of date instead of writing it.
//
//   forge build && node sdk/scripts/generate-abi.mjs [--check]

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const artifact = new URL("../../out/MORCastEscrow.sol/MORCastEscrow.json", import.meta.url);
const target = new URL("../src/abi.ts", import.meta.url);

const { abi, deployedBytecode } = JSON.parse(readFileSync(artifact, "utf8"));
const codeHash = execFileSync("cast", ["keccak", deployedBytecode.object], {
  encoding: "utf8",
}).trim();

const source = `// Generated by sdk/scripts/generate-abi.mjs from the compiled MORCastEscrow contract.
// Do not edit by hand. To update: forge build && node sdk/scripts/generate-abi.mjs

/** ABI of MORCastEscrow. */
export const morcastEscrowAbi = ${JSON.stringify(abi, null, 2)} as const;

/**
 * keccak256 of MORCastEscrow's runtime code: what \`extcodehash\` returns for every deployment of
 * this version. The contract has no immutable variables, so all its deployments share this code.
 */
export const ESCROW_CODE_HASH = "${codeHash}";
`;

if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== source) {
    console.error(
      "sdk/src/abi.ts is out of date: run forge build && node sdk/scripts/generate-abi.mjs",
    );
    process.exit(1);
  }
  console.log("sdk/src/abi.ts is up to date");
} else {
  writeFileSync(target, source);
  console.log("wrote sdk/src/abi.ts");
}
