// Writes src/abi.ts from the compiled MORCastEscrow artifact. Run `forge build` first.
// With --check, exits with an error if src/abi.ts is out of date instead of writing it.
//
//   forge build && node sdk/scripts/generate-abi.mjs [--check]

import { readFileSync, writeFileSync } from "node:fs";

const artifact = new URL("../../out/MORCastEscrow.sol/MORCastEscrow.json", import.meta.url);
const target = new URL("../src/abi.ts", import.meta.url);

const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
const source = `// Generated by sdk/scripts/generate-abi.mjs from the compiled MORCastEscrow contract.
// Do not edit by hand. To update: forge build && node sdk/scripts/generate-abi.mjs

/** ABI of MORCastEscrow. */
export const morcastEscrowAbi = ${JSON.stringify(abi, null, 2)} as const;
`;

if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== source) {
    console.error(
      "sdk/src/abi.ts is out of date: run forge build && node sdk/scripts/generate-abi.mjs",
    );
    process.exit(1);
  }
  console.log("sdk/src/abi.ts is up to date");
} else {
  writeFileSync(target, source);
  console.log("wrote sdk/src/abi.ts");
}
